# Generated by Django 6.0.4 on 2026-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('passingyear', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('previouscompanyname', models.CharField(max_length=500)),
                ('experience', models.FloatField()),
                ('jobdesc', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
                ('languagesknown', models.TextField(max_length=1000)),
                ('photo', models.ImageField(default='profilephoto/user.jpg', upload_to='profilephoto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
