# Generated by Django 6.0.4 on 2026-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
