# Generated by Django 6.0.4 on 2026-05-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='img',
            field=models.ImageField(default='movies/placeholder/placeholder.img', upload_to='movies/'),
        ),
    ]
